### ISSUE TITLE
Issue faced while updating Members.md file

### ISSUE THREAD

**Issue by reddymahendra52** [Bash-Woman-Community/Welcome#11]
Hello @Bash-Woman-Community/maintainers,
I think while updating the **Members.md** file most of the members are facing this issue.
____________________________________________________________________________________________________________________
![issue](https://user-images.githubusercontent.com/61696212/103437346-a4244d00-4c4c-11eb-988d-ba8df416b50e.PNG)
____________________________________________________

Steps to resolve:
1. After completing the block in which you filled the information instead of pressing "**Enter**" and moving to next block, please give some empty spaces and then move on to next block.
2. I think this should solve the issue.

**Comment by jai-dewani** [comment]
Give 2 spaces and then press enter to be exact for a new line

**Comment by ahammadshawki8** [comment]
Give 2 or more spaces before starting a new line.

**Comment by reddymahendra52** [comment]
Yea i resolved the issue. I wanted to try to make it like documentation for those who are facing this issue.

**Comment by rish-singhal** [comment]
if the issue is resolved shouldn't it be closed?
